// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("spanpruning")
	ScopeName = "github.com/grafana/opentelemetry-collector-extras/processor/spanpruningprocessor"
)

const (
	TracesStability = component.StabilityLevelAlpha
)
