// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("ghostspan")
	ScopeName = "github.com/grafana/opentelemetry-collector-extras/processor/ghostspanprocessor"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
