// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/grafana/opentelemetry-collector-extras/processor/partialtracesamplerprocessor/internal/metadata"
	"go.opentelemetry.io/collector/component/componenttest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	tb.ProcessorPartialtracesamplerBytesEmitted.Add(context.Background(), 1)
	tb.ProcessorPartialtracesamplerBytesReceived.Add(context.Background(), 1)
	tb.ProcessorPartialtracesamplerCompressedBytesEmitted.Add(context.Background(), 1)
	tb.ProcessorPartialtracesamplerCompressedBytesReceived.Add(context.Background(), 1)
	AssertEqualProcessorPartialtracesamplerBytesEmitted(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorPartialtracesamplerBytesReceived(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorPartialtracesamplerCompressedBytesEmitted(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorPartialtracesamplerCompressedBytesReceived(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(context.Background()))
}
