// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/grafana/opentelemetry-collector-extras/processor/partialtracesamplerprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/grafana/opentelemetry-collector-extras/processor/partialtracesamplerprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                               metric.Meter
	mu                                                  sync.Mutex
	registrations                                       []metric.Registration
	ProcessorPartialtracesamplerBytesEmitted            metric.Int64Counter
	ProcessorPartialtracesamplerBytesReceived           metric.Int64Counter
	ProcessorPartialtracesamplerCompressedBytesEmitted  metric.Int64Counter
	ProcessorPartialtracesamplerCompressedBytesReceived metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ProcessorPartialtracesamplerBytesEmitted, err = builder.meter.Int64Counter(
		"otelcol_processor_partialtracesampler_bytes_emitted",
		metric.WithDescription("Total bytes of serialized traces emitted after sampling [Development]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorPartialtracesamplerBytesReceived, err = builder.meter.Int64Counter(
		"otelcol_processor_partialtracesampler_bytes_received",
		metric.WithDescription("Total bytes of serialized traces received before sampling [Development]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorPartialtracesamplerCompressedBytesEmitted, err = builder.meter.Int64Counter(
		"otelcol_processor_partialtracesampler_compressed_bytes_emitted",
		metric.WithDescription("Total gzip-compressed bytes of serialized traces emitted after sampling [Development]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorPartialtracesamplerCompressedBytesReceived, err = builder.meter.Int64Counter(
		"otelcol_processor_partialtracesampler_compressed_bytes_received",
		metric.WithDescription("Total gzip-compressed bytes of serialized traces received before sampling [Development]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
